sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t aidandonnelly/udemy-docker-kubernetes -f Dockerfile.dev .

script:
  - docker run -e CI=true aidandonnelly/udemy-docker-kubernetes npm run test -- --coverage